In [18]:
import pandas as pd

df = pd.read_csv("./data/auto-mpg.csv",header= None)

df.columns = [
    "mpg", "cylinders", "displacement", "horsepower",
    "weight", "acceleration", "model year", "origin", "name"
]

df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite

In [19]:
mpg_to_kpl = 1.60934 / 3.78541

df["kpl"] = df["mpg"] * mpg_to_kpl
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.652571
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.377143
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.652571

In [20]:
df["kpl"] = df["kpl"].round(2)
df.head(3)

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,1,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,1,plymouth satellite,7.65

In [21]:
# 자료형 변환

df.dtypes

mpg             float64
cylinders         int64
displacement    float64
horsepower          str
weight          float64
acceleration    float64
model year        int64
origin            int64
name                str
kpl             float64
dtype: object

In [22]:
df["horsepower"].unique()

<ArrowStringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0',     '?', '100.0',
 '105.0', '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00',
 '76.00', '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0',
 '112.0', '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0',
 '230.0', '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00',
 '52.00', '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
 '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0',
 '68.00', '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0',
 '103.0', '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00',
 '132.0', '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 94, dtype: str

In [23]:
import numpy as np

In [24]:
df["horsepower"] = df["horsepower"].replace("?", np.nan)
df["horsepower"].unique()

<ArrowStringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0',     nan, '100.0',
 '105.0', '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00',
 '76.00', '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0',
 '112.0', '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0',
 '230.0', '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00',
 '52.00', '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00',
 '115.0', '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0',
 '68.00', '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0',
 '103.0', '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00',
 '132.0', '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 94, dtype: str

In [25]:
df = df.dropna(subset=["horsepower"], axis = 0)

In [26]:
df["horsepower"].unique()

<ArrowStringArray>
['130.0', '165.0', '150.0', '140.0', '198.0', '220.0', '215.0', '225.0',
 '190.0', '170.0', '160.0', '95.00', '97.00', '85.00', '88.00', '46.00',
 '87.00', '90.00', '113.0', '200.0', '210.0', '193.0', '100.0', '105.0',
 '175.0', '153.0', '180.0', '110.0', '72.00', '86.00', '70.00', '76.00',
 '65.00', '69.00', '60.00', '80.00', '54.00', '208.0', '155.0', '112.0',
 '92.00', '145.0', '137.0', '158.0', '167.0', '94.00', '107.0', '230.0',
 '49.00', '75.00', '91.00', '122.0', '67.00', '83.00', '78.00', '52.00',
 '61.00', '93.00', '148.0', '129.0', '96.00', '71.00', '98.00', '115.0',
 '53.00', '81.00', '79.00', '120.0', '152.0', '102.0', '108.0', '68.00',
 '58.00', '149.0', '89.00', '63.00', '48.00', '66.00', '139.0', '103.0',
 '125.0', '133.0', '138.0', '135.0', '142.0', '77.00', '62.00', '132.0',
 '84.00', '64.00', '74.00', '116.0', '82.00']
Length: 93, dtype: str

In [27]:
df["horsepower"] = df["horsepower"].astype("float")
df["horsepower"]

0      130.0
1      165.0
2      150.0
3      150.0
4      140.0
       ...
393     86.0
394     52.0
395     84.0
396     79.0
397     82.0
Name: horsepower, Length: 392, dtype: float64

In [28]:
df["origin"].unique()

array([1, 3, 2])

In [29]:
df["origin"].value_counts()

origin
1    245
3     79
2     68
Name: count, dtype: int64

In [31]:
df["origin"].value_counts(dropna=False)

origin
1.0    242
3.0     79
2.0     68
NaN      3
Name: count, dtype: int64

In [30]:
df["origin"] = df["origin"].rename(
    {
        1 : "USA",
        2 : "EU",
        3 : "JAPAN"
    }
)

In [32]:
df["origin"].unique()

array([ 1., nan,  3.,  2.])

In [33]:
df["origin"].dtypes

dtype('float64')

In [34]:
df.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model year,origin,name,kpl
0,18.0,8,307.0,130.0,3504.0,12.0,70,1.0,chevrolet chevelle malibu,7.65
1,15.0,8,350.0,165.0,3693.0,11.5,70,NaN,buick skylark 320,6.38
2,18.0,8,318.0,150.0,3436.0,11.0,70,NaN,plymouth satellite,7.65
3,16.0,8,304.0,150.0,3433.0,12.0,70,NaN,amc rebel sst,6.80
4,17.0,8,302.0,140.0,3449.0,10.5,70,1.0,ford torino,7.23

In [35]:
df["origin"].isnull().sum()

np.int64(3)

In [36]:
df["origin"].astype("category")

0      1.0
1      NaN
2      NaN
3      NaN
4      1.0
      ...
393    1.0
394    2.0
395    1.0
396    1.0
397    1.0
Name: origin, Length: 392, dtype: category
Categories (3, float64): [1.0, 2.0, 3.0]