In [1]:
import pandas as pd

In [2]:
# 시리즈 = pandas.Series(데이터)
# 데이터프레임 = pandas.dataframe(데이터)

In [3]:
dict_data = {
    "c0" : [1, 2, 3],
    "c1" : [4, 5, 6],
    "c2" : [7, 8, 9],
    "c3" : [10, 11, 12],
    "c4" : [13, 14, 15]
}

df = pd.DataFrame(dict_data)
print(type(df))
print(df)

<class 'pandas.DataFrame'>
   c0  c1  c2  c3  c4
0   1   4   7  10  13
1   2   5   8  11  14
2   3   6   9  12  15

In [4]:
# 행 인덱스/ 열 이름 설정

import pandas as pd

data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(data, index = ["준서", "예은"], columns=["나이", "성별", "학교"])
print(df)

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [5]:
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [6]:
df.index

Index(['준서', '예은'], dtype='str')

In [7]:
df.columns

Index(['나이', '성별', '학교'], dtype='str')

In [10]:
df.index = ["학생 1", "학생 2"]
df

      나이 성별   학교
학생 1  15  남  덕영중
학생 2  17  여  수리중

In [12]:
df.columns = ["연령", "남녀", "소속"]
df

      연령 남녀   소속
학생 1  15  남  덕영중
학생 2  17  여  수리중

In [13]:
import pandas as pd

data = [
    [15, "남", "덕영중"],
    [17, "여", "수리중"]
]

df = pd.DataFrame(data, index = ["준서", "예은"], columns=["나이", "성별", "학교"])
df

    나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [18]:
df = df.rename(columns = {"나이" : "연령", "성별" : "남여", "학교" : "소속"})
df

    연령 남여   소속
준서  15  남  덕영중
예은  17  여  수리중

In [20]:
df.rename(index = {
    "준서" : "학생 1",
    "예은" : "학생 2"
})
df

    연령 남여   소속
준서  15  남  덕영중
예은  17  여  수리중

In [22]:
# 행/열 삭제
# 행삭제 : dataframe객체, drop(행 인덱스 또는 배열, axis = 0 Ehsms axis = "index")
# 열삭제 : dataframe객체, drop(열 이름 또는 배열, axis = 1 Ehsms axis = "columns")

import pandas as pd

exam_data = {
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data, index = ["서준", "우현", "인아"])
df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [24]:
df2 = df.copy()
df2 = df2.drop("우현")
df2

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [26]:
df3 = df.copy()
df3 = df3.drop(["우현", "인아"], axis = 0)
df3

    수학  영어  음악   체육
서준  90  98  85  100

In [27]:
df4 = df.copy()
df4 = df4.drop(["우현", "인아"], axis = "index")
df4

    수학  영어  음악   체육
서준  90  98  85  100

In [28]:
df5 = df.copy()
df5 = df5.drop(index = ["우현"])
df5

    수학  영어   음악   체육
서준  90  98   85  100
인아  70  95  100   90

In [31]:
# 열 삭제

df2 = df.copy()
df2.drop("수학", axis = 1)

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [32]:
df3 = df.copy()
df3.drop(["영어", "음악"], axis = 1)

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [33]:
df4 = df.copy()
df4.drop(["영어", "음악"], axis = "columns")

    수학   체육
서준  90  100
우현  80   90
인아  70   90

In [34]:
df5 = df.copy()
df5 = df5.drop(columns = ["수학"])
df5

    영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [35]:
# 행 선택

df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [36]:
df.loc["서준"]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [37]:
type(df.loc["서준"])

pandas.Series

In [40]:
label1 = df.loc["서준"]
position1 = df.iloc[0]

print(label1)
print()
print(position1)

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [41]:
print(df.loc[["서준", "우현"]])
print()
print(df.iloc[[0,1]])

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [43]:
type(df.loc[["서준", "우현"]])

pandas.DataFrame

In [ ]:
# 행 선택

print(df.loc["서준" : "우현"])
print()
print(df.iloc[0:1])

    수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

    수학  영어  음악   체육
서준  90  98  85  100

In [45]:
# 열 선택

df

    수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [46]:
df["수학"]

서준    90
우현    80
인아    70
Name: 수학, dtype: int64

In [47]:
type(df["수학"])

pandas.Series

In [ ]:
df.영어
# df [" 영 어 "]

서준    98
우현    89
인아    95
Name: 영어, dtype: int64

In [49]:
df[["영어", "체육"]]

    영어   체육
서준  98  100
우현  89   90
인아  95   90

In [50]:
print(df["영어"])
print()
print(df[["영어"]])

서준    98
우현    89
인아    95
Name: 영어, dtype: int64

    영어
서준  98
우현  89
인아  95

In [51]:
# 원소 선택

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [100, 90, 90]
}

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [52]:
print(df.loc[0:2])
print()
print(df.iloc[0:2])

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

   이름  수학  영어  음악   체육
0  서준  90  98  85  100
1  우현  80  89  95   90

In [58]:
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [59]:
df.loc["서준"]
df.iloc[0]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [60]:
# df.loc["서준", "음악"]
print(df.loc["서준","음악"])
print()
print(df.iloc[0,2])

85

85

In [61]:
df.loc["서준", ["음악", "체육"]]
print(df.iloc[0, []])

Series([], Name: 서준, dtype: float64)

In [62]:
print(df.loc["서준","음악" : "체육"])
print()
print(df.iloc[0, 2:])

음악     85
체육    100
Name: 서준, dtype: int64

음악     85
체육    100
Name: 서준, dtype: int64

In [64]:
# 열 추가
# 데이터프레임 객체["열이름"] = 데이터값

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [100, 90, 90]
}

import pandas as pd

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [65]:
df["국어"] = 80
df

   이름  수학  영어   음악   체육  국어
0  서준  90  98   85  100  80
1  우현  80  89   95   90  80
2  인아  70  95  100   90  80

In [67]:
df["미술"] = [80, 90, 100]
df

   이름  수학  영어   음악   체육  국어   미술
0  서준  90  98   85  100  80   80
1  우현  80  89   95   90  80   90
2  인아  70  95  100   90  80  100

In [69]:
# 행 추가
# DataFrame객체.loc["행이름"] = 데이터 값

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [100, 90, 90]
}

import pandas as pd

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [70]:
df.loc[3] = 0
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0

In [71]:
df.loc[4] = ["동규", 90, 80, 70, 60]
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90
3   0   0   0    0    0
4  동규  90  80   70   60

In [72]:
df.loc["행5"] = df.loc[1]
df

    이름  수학  영어   음악   체육
0   서준  90  98   85  100
1   우현  80  89   95   90
2   인아  70  95  100   90
3    0   0   0    0    0
4   동규  90  80   70   60
행5  우현  80  89   95   90

In [83]:
# 원소값 변경

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [100, 90, 90]
}

import pandas as pd

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [84]:
df = df.set_index("이름")
df

    수학  영어   음악   체육
이름
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [85]:
df.iloc[0, 3] = 80
df

    수학  영어   음악  체육
이름
서준  90  98   85  80
우현  80  89   95  90
인아  70  95  100  90

In [88]:
df.loc["서준", "체육"] = 90
df

    수학  영어   음악  체육
이름
서준  90  98   85  90
우현  80  89   95  90
인아  70  95  100  90

In [92]:
df.loc["서준",["음악", "체육"]] = 50
df

    수학  영어   음악  체육
이름
서준  90  98   50  50
우현  80  89   95  90
인아  70  95  100  90

In [93]:
df.loc["서준", ["음악", "체육"]] = 100, 50
df

    수학  영어   음악  체육
이름
서준  90  98  100  50
우현  80  89   95  90
인아  70  95  100  90

In [94]:
# 행과 열의 위치 바꾸기
# DataFrame객체.transpose()
# DataFrame객체.T

exam_data = {
    "이름" : ["서준", "우현", "인아"],
    "수학" : [90, 80, 70],
    "영어" : [98, 89, 95],
    "음악" : [ 85, 95, 100],
    "체육" : [100, 90, 90]
}

import pandas as pd

df = pd.DataFrame(exam_data)
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [95]:
df = df.transpose()
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [96]:
df = df.T
df

   이름  수학  영어   음악   체육
0  서준  90  98   85  100
1  우현  80  89   95   90
2  인아  70  95  100   90

In [97]:
df = df.T
df

      0   1    2
이름   서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90